### ISSUE TITLE
Timeout errors when rendering large digrams

### ISSUE THREAD

**Issue by kareldonk** [awaragi/eleventy-plugin-plantuml#7]
For large diagrams, when sending a request to the plantuml server, it can take a long time to get the result back. This results in 504 timeout errors breaking the 11ty build.

The `sync-request` package used to get the diagram from the server supports passing options, where you can set number of retries and timeout settings. 
It would be nice if it were possible to send these options via the config options for this plugin, which are then passed along to `sync-request`.

**Comment by awaragi** [comment]
I will try to get it done ASAP. Thanks for reporting it.

**Comment by awaragi** [comment]
are you sure that the issue from timeout at the generator side? the default value for the timeout is false which means that sync-request does not time out.  I am going to add extra options to pass through to the request class

**Comment by awaragi** [comment]
released 1.16 which has requestTimeout and requestSocketTimeout that are passthrough to the request class. By default they are undefined which will defaults to request class defaults (mouthful...).

**Comment by kareldonk** [comment]
thanks i will try it out

**Comment by kareldonk** [comment]
Any chance you can also expose the following settings from `sync-request` in the same way?
- `retry`
- `retryDelay`
- `maxRetries`

**Comment by awaragi** [comment]
changed the config object to have "request" field which is passed as is to the sync-request function. So you can do whatever you want with it. See updated README documentation.

**Comment by kareldonk** [comment]
A combination of longer timeout values and enabling retries fixed the issue I was having. Thanks :)
